<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Jnana</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <EnableMsixTooling>true</EnableMsixTooling>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Workbench\Controls\NuGetsTreeView\**" />
    <EmbeddedResource Remove="Workbench\Controls\NuGetsTreeView\**" />
    <None Remove="Workbench\Controls\NuGetsTreeView\**" />
    <Page Remove="Workbench\Controls\NuGetsTreeView\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Assets\Styles\LonghornTitleBar.xaml" />
    <None Remove="Controls\MarkdownPane.xaml" />
    <None Remove="Core\Navigation\NavigationHost.xaml" />
    <None Remove="Views\Tiles\NuGetTile.xaml" />
    <None Remove="Views\Tiles\WorkbenchTile.xaml" />
    <None Remove="Workbench\Components\QuickLaunchBar.xaml" />
    <None Remove="Workbench\Controls\FloatingStatusBar.xaml" />
    <None Remove="Workbench\Controls\NuGetTreeView.xaml" />
    <None Remove="Workbench\Pages\GitHub\GitHubPage.xaml" />
    <None Remove="Workbench\Pages\NuGets\NuGetPackageCard.xaml" />
    <None Remove="Workbench\Pages\NuGets\NuGetsPage.xaml" />
    <None Remove="Workbench\Pages\Samples\SampleCard.xaml" />
    <None Remove="Workbench\Pages\Samples\SamplesPage.xaml" />
    <None Remove="Workbench\Pages\SysInfo\SysInfoPage.xaml" />
    <None Remove="Workbench\Pages\ToolsAndUtilitiesPage.xaml" />
    <None Remove="Workbench\Pages\VoidPage.xaml" />
    <None Remove="Workbench\Pages\WorkbenchPage.xaml" />
    <None Remove="Workbench\Pages\Workbench\DisassemblyPage.xaml" />
    <None Remove="Workbench\Pages\Workbench\TugorPage.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\StoreLogo.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="CommunityToolkit.WinUI.UI.Controls.Markdown" Version="7.1.2" />
    <PackageReference Include="fuselibs-desktop-fonts" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.11" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
    <PackageReference Include="NuGet.Common" Version="7.9.0" />
    <PackageReference Include="NuGet.Configuration" Version="7.9.0" />
    <PackageReference Include="NuGet.ProjectModel" Version="7.9.0" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Private.Uri" Version="4.3.2" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="Vanara.Core" Version="5.0.6" />
    <PackageReference Include="Vanara.PInvoke.Shared" Version="5.0.0" />
    <PackageReference Include="Vanara.PInvoke.Shell32" Version="5.0.6" />
    <PackageReference Include="Vanara.PInvoke.User32" Version="5.0.6" />
    <PackageReference Include="Vanara.Windows.Shell" Version="5.0.6" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="Workbench\Pages\SysInfo\SysInfoPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Workbench\Pages\Samples\SampleCard.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Workbench\Pages\Samples\SamplesPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Workbench\Pages\NuGets\NuGetPackageCard.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Workbench\Pages\NuGets\NuGetsPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Workbench\Pages\GitHub\GitHubPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Workbench\Pages\VoidPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Workbench\Components\QuickLaunchBar.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Workbench\Pages\WorkbenchPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Core\Navigation\NavigationHost.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Workbench\Controls\NuGetTreeView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <WebView2DispatchAdapterNamespace>jnana.vanara</WebView2DispatchAdapterNamespace>
  </PropertyGroup>

  <!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>

  <!-- Publish Properties -->
  <PropertyGroup>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
    <PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
    <PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
    <StartupObject>Jnana.Program</StartupObject>
    <ApplicationIcon>Assets\Icons\Vamara Icon.ico</ApplicationIcon>
    <IncludeSymbols>True</IncludeSymbols>
    <PackageIcon>Vamara Icon.ico</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>debug build - do not use in productive environment</PackageReleaseNotes>
    <AssemblyVersion>1.268.1.0</AssemblyVersion>
    <FileVersion>1.268.1.0</FileVersion>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>
  <ItemGroup>
    <PRIResource Remove="Workbench\Controls\NuGetsTreeView\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="Assets\Styles\LonghornTitleBar.xaml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="Assets\Icons\Vamara Icon.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Workbench\Pages\Workbench\DisassemblyPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Controls\MarkdownPane.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Workbench\Pages\ToolsAndUtilitiesPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Workbench\Pages\Workbench\TugorPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Workbench\Controls\FloatingStatusBar.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Views\Tiles\NuGetTile.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Views\Tiles\WorkbenchTile.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Assets\Styles\LonghornTitleBar.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Assets\Fonts\" />
  </ItemGroup>
</Project>