<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<EnableMsixTooling>true</EnableMsixTooling>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<UseWinUI>true</UseWinUI>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="ICSharpCode.Decompiler" Version="10.0.1.8346" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3912.50" />
		<PackageReference Include="Microsoft.Win32.SystemEvents" Version="10.0.7" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260317003" />
		<PackageReference Include="NuGet.Common" Version="7.3.1" />
		<PackageReference Include="NuGet.Protocol" Version="7.3.1" />
		<PackageReference Include="Vanara.Core" Version="5.0.4" />
		<PackageReference Include="Vanara.PInvoke.SearchApi" Version="5.0.4" />
		<PackageReference Include="Vanara.PInvoke.Shell32" Version="5.0.4" />
		<PackageReference Include="Vanara.PInvoke.User32" Version="5.0.4" />
		<PackageReference Include="Vanara.Windows.Shell" Version="5.0.4" />
		<PackageReference Include="Vanara.WinUI.Extensions" Version="5.0.4" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Resources\i18n\" />
		<Folder Include="Templates\RyderShell\Project\" />
	</ItemGroup>
	<ItemGroup>
		<Content Update="Assets\Vanara\Insert_Amiga-Disk.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Update="Assets\Vanara\WinUi-Sailing.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Vanara\Controls\FeatureTile.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Templates\RyderShell\Styles\MainPage.xaml">
			<SubType>Designer</SubType>
		</Page>
		<Page Update="Templates\RyderShell\Views\MainPage.xaml">
			<SubType>Designer</SubType>
		</Page>
		<Page Update="Views\ApiExplorerPage.xaml">
			<SubType>Designer</SubType>
		</Page>
		<Page Update="Views\SettingsPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\AboutPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\SamplesPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\StartPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\ShellPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="DOCS\docs.assets\WinUi-Sailing.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Vanara\Styles\NavButtonStyle.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Vanara\Styles\SidebarControl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Vanara\Controls\Shell32AppBar.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Vanara\Controls\FloatingStatusBar.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
</Project>
