<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<EnableMsixTooling>true</EnableMsixTooling>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<UseWinUI>true</UseWinUI>
		<ApplicationIcon>Assets\Vanara\MFC-App.ico</ApplicationIcon>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<DebugSymbols>false</DebugSymbols>
		<DebugType>portable</DebugType>
		<DefineConstants>TRACE</DefineConstants>
		<Deterministic>true</Deterministic>
		<Optimize>true</Optimize>
		<PublishReadyToRun>true</PublishReadyToRun>
		<PublishTrimmed>false</PublishTrimmed>
		<UseWindowsForms>false</UseWindowsForms>
		<UseWPF>false</UseWPF>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="Resources\**" />
		<Compile Remove="Vanara.WinUI.Extensions\**" />
		<EmbeddedResource Remove="Resources\**" />
		<EmbeddedResource Remove="Vanara.WinUI.Extensions\**" />
		<None Remove="Resources\**" />
		<None Remove="Vanara.WinUI.Extensions\**" />
		<Page Remove="Resources\**" />
		<Page Remove="Vanara.WinUI.Extensions\**" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Labs.WinUI.Controls.MarkdownTextBlock" Version="0.1.260529-build.2632" />
		<PackageReference Include="CommunityToolkit.Labs.WinUI.Controls.Ribbon" Version="0.1.260529-build.2632" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="CommunityToolkit.WinUI.Behaviors" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Collections" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.Sizers" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Converters" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.DeveloperTools" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Extensions" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Media" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Triggers" Version="8.2.251219" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
		<PackageReference Include="Vanara.Core" Version="5.0.5" />
		<PackageReference Include="Vanara.PInvoke.Shell32" Version="5.0.5" />
		<PackageReference Include="Vanara.PInvoke.User32" Version="5.0.5" />
		<PackageReference Include="Vanara.Windows.Shell" Version="5.0.5" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="DOCS\docs.assets\Screenshots\" />
		<Folder Include="DOCS\Templates\" />
		<Folder Include="Styles\Backgrounds\" />
		<Folder Include="Vanara\Controls\Shell32\" />
	</ItemGroup>
	<ItemGroup>
		<Content Update="Assets\Vanara\Insert_Amiga-Disk.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Update="Assets\Vanara\WinUi-Sailing.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Vanara\Controls\FeatureTile.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\SettingsPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\NuGetsPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\SamplesPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\StartPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\GitHubPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="DOCS\docs.assets\WinUi-Sailing.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Vanara\Styles\NavButtonStyle.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Vanara\Styles\SidebarControl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Vanara\Controls\Shell32AppBar.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Vanara\Controls\FloatingStatusBar.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<PRIResource Remove="Resources\**" />
	</ItemGroup>
	<ItemGroup>
		<None Remove="DOCS\docs.assets\WinForms Sampler.zip" />
		<None Remove="DOCS\ReadMe.de.md" />
		<None Remove="Vanara\Controls\NuGetPackageCard.xaml" />
		<None Remove="Vanara\Controls\Shell32\ShellInfoPanel.xaml" />
		<None Remove="Views\DockPanels\DebugModeFloatingPanel.xaml" />
		<None Remove="Views\DockPanels\FileWatcherPanel.xaml" />
		<None Remove="Views\DockPanels\InspectorView.xaml" />
		<None Remove="Views\ShellPage.xaml" />
		<None Remove="Views\UtilitiesPage.xaml" />
		<None Remove="Views\VoidPage.xaml" />
	</ItemGroup>
	<ItemGroup>
	  <Content Include="DOCS\docs.assets\WinForms Sampler.zip">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
	<ItemGroup>
	  <Resource Include="DOCS\ReadMe.de.md">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\GuruMeditationDialog.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Views\DockPanels\QuickLaunchBar.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Views\DockPanels\FileWatcherPanel.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Vanara\Controls\Shell32\ShellInfoPanel.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Vanara\Controls\NuGetPackageCard.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Views\Tabs\TextEditorTab.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Views\Pages\FileManagementOpus.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Views\DockPanels\DebugModeFloatingPanel.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Views\DockPanels\InspectorView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Views\VoidPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\ShellPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\DisassemblerPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\UtilitiesPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
	  <PRIResource Remove="Vanara.WinUI.Extensions\**" />
	</ItemGroup>
</Project>
